# site settings
title: Maxime Dahirel
subtitle: Behavioural and Evolutionary Ecology
description: I am a behavioural and evolutionary ecologist interested in the causes and consequences of individual-, population- and species-level variation in behaviour, morphology and life-history. My research is especially focused on dispersal, as a key trait bridging ecological and evolutionary dynamics, and on the role of behaviour in explaining species’ ability (or inability) to persist in cities.
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mdahirel/
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mdahirel

# build settings
markdown: kramdown

sass:
  style: compressed
