# site settings
title: Maxime Dahirel
subtitle: 
description: I am a behavioural and evolutionary ecologist interested in the causes and consequences of dispersal and in adaptation to city life.
url: # the base hostname & protocol for your site
email: maxime.dahirel [at] yahoo.fr
author: Dr Maxime Dahirel
street_address: New address coming soon...
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mdahirel/
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mdahirel

# build settings
markdown: kramdown

sass:
  style: compressed
