# site settings
title: Maxime Dahirel
subtitle: 
description: I am a behavioural and evolutionary ecologist interested in the causes and consequences of dispersal and in adaptation to city life.
url: # the base hostname & protocol for your site
email: maxime.dahirel [at] inra.fr
author: Dr Maxime Dahirel
street_address: Institut Sophia Agrobiotech <br/> INRA PACA <br/> 400 route des Chappes <br/> BP 167
city: 06903 Sophia Antipolis Cedex
state: 
zip_code: 
country: FRANCE
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mdahirel/
gitlab_url:
googlescholar_url: https://scholar.google.fr/citations?user=ZhTCQFAAAAAJ&hl 
instagram_url: 
linkedin_url: 
orcid_url: http://orcid.org/0000-0001-8077-7765
pinterest_url:
publons_url: https://publons.com/a/1196421/
researchgate_url: https://www.researchgate.net/profile/Maxime_Dahirel
slack_url:
twitter_url: https://twitter.com/mdahirel

# build settings
markdown: kramdown

sass:
  style: compressed
