project:
  type: website
  output-dir: docs

website:
  title: "Maxime Dahirel"
  favicon: images/icon.png
  navbar:
    pinned: true
    foreground: "#ffffff"
    background: "#4caf50"
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - text: Research topics
        menu: 
          - urban-ecology.qmd
          - dispersal.qmd
      - text: Study species
        menu: 
         - snails.qmd
         - spiders.qmd
      - href: publications.qmd
        text: Publications
      - href: c_v.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer: "Content by Maxime Dahirel, unless specified · Tab icon by [Gareth Monger](http://phylopic.org/image/cdc067a4-c2cc-4962-b330-2c9d02d245cb/) [(CC-BY 3.0)](https://creativecommons.org/licenses/by/3.0/) for [Phylopic](http://phylopic.org/) · Made using [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    linkcolor: "#39833c"
    css: styles.css
    toc: true

editor: visual

